// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbbosewdaffjrhdqdgio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiYm9zZXdkYWZmanJoZHFkZ2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTM3ODAsImV4cCI6MjA3MjA2OTc4MH0.SRJLo06tLQjgvr4NggZL9b8b93XvNFQcOAi4oiEH0lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});